vich_uploader:
    db_driver: orm
    mappings:
        article_images:
            uri_prefix:         '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/%app.path.article_images%'
        galerie_images:
            uri_prefix:         '%app.path.galerie_images%'
            upload_destination: '%kernel.project_dir%/%app.path.galerie_images%'
        cv_pdf:
            uri_prefix:         '%app.path.cv_pdf%'
            upload_destination: '%kernel.project_dir%/%app.path.cv_pdf%'
        lm_pdf:
            uri_prefix:         '%app.path.lm_pdf%'
            upload_destination: '%kernel.project_dir%/%app.path.lm_pdf%'